# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\1_Master\1_1_Masterarbeit\SW\Python\MPC_Energy_Management/secondWindowDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_secondaryWindow(object):
    def setupUi(self, secondaryWindow):
        secondaryWindow.setObjectName("secondaryWindow")
        secondaryWindow.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(secondaryWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(secondaryWindow)
        self.tabWidget.setObjectName("tabWidget")
        self.buildingTab = QtWidgets.QWidget()
        self.buildingTab.setObjectName("buildingTab")
        self.tabWidget.addTab(self.buildingTab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.widget = QtWidgets.QWidget(secondaryWindow)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(secondaryWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(secondaryWindow)

    def retranslateUi(self, secondaryWindow):
        _translate = QtCore.QCoreApplication.translate
        secondaryWindow.setWindowTitle(_translate("secondaryWindow", "secondaryWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buildingTab), _translate("secondaryWindow", "Building"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("secondaryWindow", "Battery"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("secondaryWindow", "Electric Vehicle"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("secondaryWindow", "Solar Panel"))
        self.pushButton.setText(_translate("secondaryWindow", "Save"))
        self.pushButton_2.setText(_translate("secondaryWindow", "Cancel"))
